# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[cmd_duration]
min_time = 500
format = "underwent [$duration](bold yellow)"

[container]
format = "[$symbol \\[$name\\]]($style) "

[docker_context]
format = "via [🐋 $context](blue bold)"

[hostname]
ssh_only = false
format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[localip]
ssh_only = false
format = "@[$localipv4](bold red) "
disabled = false

[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"

[shell]
nu_indicator = "🪙 "
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = false

[sudo]
style = "bold green"
symbol = "🛹 "
disabled = false
